Feat/messages read
idoleg/messenger-backend pull request #19
Opened 2019-04-22 14:41 UTC by antropit

NOT READY, DO NOT APPLY! ONLY TO FIND ERRORS

2019-04-23 19:45 UTC, superpike requested changes

2019-04-23 19:45 UTC, superpike commented on app/Controllers/WebSocket/MessageController.ts
> +            const { id, sender } = payload;
У тебя получается id - это группа, а sender - это директ?
но это не так...
Я понимаю, что:
id - это id сообщения, которое прочитал пользователь
sender - это id группы или директа

2019-04-23 19:45 UTC, superpike commented on app/Controllers/WebSocket/MessageController.ts
> +                await members.forEach(async (el) => {
Если кто-то прочитал, то не надо всем в группе ставить "прочитано". Прочитал только один из всех

2019-04-23 19:45 UTC, superpike commented on app/Controllers/WebSocket/MessageController.ts
> +                    const memberId = el.member.toString();
Нет смысла переводить в строку, т.к. потом переводится все обратно в ObjectId, если строка - а это лишние действия

2019-04-23 19:45 UTC, superpike commented on app/Controllers/WebSocket/MessageController.ts
> +                    if ((!el.member.equals(client.user.model._id)) && Socket.rooms.has(`user:${memberId}`)) {
Это лишнее...зачем мы отправляем каждому участнику группы, что кто-то прочитал сообщение?

2019-04-23 19:45 UTC, superpike commented on app/Controllers/WebSocket/MessageController.ts
> +            result(true, { message: payload, sent_at: new Date() });
```suggestion
            result(true, { message: payload });
```

2019-04-24 11:55 UTC, antropit commented on app/Controllers/WebSocket/MessageController.ts
> +            const { id, sender } = payload;
Нет. В findChatByUserGroupId(user, id) два параметра в случае группы берется (memberId, id) в случае директа берется (sender, id), т.е. id это или group или direct

2019-04-24 12:03 UTC, antropit commented on app/Controllers/WebSocket/MessageController.ts
> +                    const memberId = el.member.toString();
Тогда получается проверка на группу не нужна, код становиться одинаков:
                await UserChats.resetChatUnread(sender, id);
                const room = Socket.rooms.get(`user:${sender}`);
                if (room) {
                    room.emit("messages:read", { id, recipient });
                }

2019-04-24 12:04 UTC, antropit commented on app/Controllers/WebSocket/MessageController.ts
> +                    if ((!el.member.equals(client.user.model._id)) && Socket.rooms.has(`user:${memberId}`)) {
эта ветка совсем пока удаляется на основании предыдущего коммента

2019-04-24 15:49 UTC, superpike requested changes

2019-04-24 15:49 UTC, superpike commented on app/Controllers/WebSocket/MessageController.ts
> +            const { id, sender } = payload;
GroupMembers.isMember(id, client.user.model) - а тут id чего ты передаешь?

2019-04-24 17:41 UTC, antropit commented
В GroupMembers.isMember(id, client.user.model) id это group оно же исходя из:
`UserChatSchema.static("findChatByUserGroupId", async function(user: string | IUser, id: string) {
    const userId = getRightId(user);
    const userGroupId = getRightId(id);
    return await this.findOne({
        user: userId,
        $or: [
            { group: userGroupId },
            { direct: userGroupId },
        ],
    });
});`

2019-04-26 18:12 UTC, antropit commented on app/Controllers/WebSocket/MessageController.ts
> +            const { id, sender } = payload;
В GroupMembers.isMember(id, client.user.model) id это group исходя из:

![image](https://user-images.githubusercontent.com/33189108/56681242-970e3700-66d1-11e9-9b41-55b045b5fbf9.png)

2019-05-04 05:51 UTC, antropit commented
![](https://github.trello.services/images/mini-trello-icon.png) [Вебсокеты: прочитанные сообщения](https://trello.com/c/EGf25Atv/23-%D0%B2%D0%B5%D0%B1%D1%81%D0%BE%D0%BA%D0%B5%D1%82%D1%8B-%D0%BF%D1%80%D0%BE%D1%87%D0%B8%D1%82%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D1%8F)

2019-06-14 13:25 UTC, closed without merging